# Generated by Django 5.2.5 on 2026-08-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('visitors', models.PositiveIntegerField()),
                ('spend_millions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_nights', models.DecimalField(decimal_places=1, max_digits=4)),
                ('yoy_change', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'ordering': ['-visitors', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'year'), name='unique_market_year')],
            },
        ),
    ]
