# Generated by Django 5.2.5 on 2026-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('year', models.PositiveSmallIntegerField()),
                ('arrivals', models.BigIntegerField(blank=True, null=True)),
                ('receipts_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source', models.CharField(default='World Bank / UN Tourism', max_length=120)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-arrivals', 'country_name'],
            },
        ),
        migrations.DeleteModel(
            name='MarketMetric',
        ),
        migrations.AddIndex(
            model_name='tourismmetric',
            index=models.Index(fields=['year', 'region'], name='tourism_tou_year_4d1962_idx'),
        ),
        migrations.AddIndex(
            model_name='tourismmetric',
            index=models.Index(fields=['country_name'], name='tourism_tou_country_2d7f7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tourismmetric',
            constraint=models.UniqueConstraint(fields=('country_code', 'year'), name='unique_country_year'),
        ),
    ]
